INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (0, 'VM', 'Passat', 150000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (1, 'BMW', 'M3', 278000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (2, 'Mercedes', 'Class E', 299000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (3, 'Toyota', 'Corola', 12500)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (4, 'BMW', 'Cross', 235000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (5, 'Mercedes', 'Benz', 350000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (6, 'Renault', 'Megane', 15000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (7, 'Tesla', 'Model S', 30000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (8, 'Tesla', 'CyberTruck', 100000)
INSERT [dbo].[car] ([Id], [Vendor], [Model], [Price]) VALUES (9, 'VW', 'Golf GTI', 90000)